blog/urls.py
"""
URLs for entries, categories and feeds in the blog.

"""

from django.conf.urls import patterns
from django.conf.urls import url

from blog import views

from blog.feeds import CategoryFeed
from blog.feeds import EntriesFeed

urlpatterns = patterns('',
                       url(r'^$',
                           views.BlogHome.as_view(),
                           name='blog_home'),
                       url(r'^archive/$',
                           views.EntryArchiveIndex.as_view(),
                           name='blog_entry_archive_index'),
                       url(r'^entry/(?P<slug>[-\w]+)/$',
                           views.EntryDetail.as_view(),
                           name='blog_entry_detail'),
                       )

urlpatterns += patterns('',
                        url(r'^category/$',
                            views.CategoryList.as_view(),
                            name='blog_category_list'),
                        url(r'^category/(?P<slug>[-\w]+)/$',
                            views.CategoryDetail.as_view(),
                            name='blog_category_detail'),
                        )

urlpatterns += patterns('',
                        url(r'^rss/$',
                            EntriesFeed(),
                            name='blog_feeds_entries'),
                        url(r'^rss/(?P<slug>[-\w]+)/$',
                            CategoryFeed(),
                            name='blog_feeds_category'),
                        )

contact/urls.py
from django.conf.urls import url

from .views import SubmitView, ThanksView


urlpatterns = [
    url(r'^$', SubmitView.as_view(), name='form'),
    url(r'^thanks/$', ThanksView.as_view(), name='thanks'),
]

shadow/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from shadow import views

urlpatterns = patterns('',
                       url(r'^$',
                           views.Home.as_view(),
                           name='home'),
                       url(r'^blog/',
                           include('blog.urls')),
                       url(r'^expenses/',
                           include('expenses.urls')),
                       url(r'^pages/',
                           include('django.contrib.flatpages.urls')),
                       url(r'^admin/',
                           include(admin.site.urls)),
                       url(r'^contact/',
                           include('contact.urls',
                               namespace='contact',
                               app_name='contact')),
                       )

urlpatterns += patterns('',
                        url('^20',
                            views.old_blog,
                            name = 'old_blog'),
                        )

templates/base.html
<!DOCTYPE HTML>
{% load sitemetrics %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title_heading %}{{ heading_meta }} {{ site.name }}{% endblock title_heading %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL }}css/shadow.css" rel="stylesheet" media="screen">
{% block extrahead %} {% endblock extrahead %} 
</head>
<body>
    <div class="container">
    {% include "navbar.html" %}

        <section class="row" id="content">
            <article class="container">{% block content %}{% endblock content %}</article>
        </section>

    {% include "footer.html" %}
    </div>

    <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

    {% block extrajs %}{% endblock extrajs %}

    {% sitemetrics %}
</body>
</html>

templates/footer.html
<footer class="footer">
  <p>&copy 2015 Karambir Singh Nain</p>
</footer>

templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Hi, I am Karambir and this is my personal website.</h1>
    <p>I am a Web Developer and a Dota2 amateur.
    You can find me on various social networking sites by username <strong>akarambir</strong>.</p>
    <p>I write my experiences on my <a href="{% url 'blog_home' %}">blog</a> and collect all sorts of useful links
    and information <a href="https://pinboard.in/u:karambir/">here</a>.</p>
    <p>In my leisure time I like to play Dota2 and build some cool projects. See them <a href="/pages/projects/">here</a>.</p>
    <p>Check out my <a href="/pages/about/" class="btn btn-sm btn-primary">Resume</a> or connect with me .</p>
</div>
{% endblock content %}

templates/navbar.html
{% load flatpages %}
{% get_flatpages as flatpages %}
<header class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">{{ site.name|default:"Shadow" }}</a>
    </div>
    <nav class="navbar-collapse collapse" role="navigation">
        <ul class="nav navbar-nav navbar-right">
            <li class="{% ifequal request.path "/" %}active{% endifequal %}"><a href="/">Home</a></li>
            <li class="{% if "/blog" in request.path %}active{% endif %}"><a href="{% url 'blog_home' %}">Blog</a></li>
            <li class="{% if "/contact" in request.path %}active{% endif %}"><a href="{% url 'contact:form' %}">Contact</a></li>
            {% for page in flatpages %}
            <li class="{% ifequal request.path "/pages"|add:page.url %}active{% endifequal %}"><a href="/pages{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
        </ul>
    </nav>
  </div>
</header>

templates/pagination.html
{% if is_paginated %}
    <div class="row-fluid">
        <ul class="pager">
            {% if page_obj.has_previous %}
            <li class="previous">
                <a href="?page={{ page_obj.previous_page_number }}">&larr; previous</a>
            </li>
            {% else %}
            <li class="previous disabled">
                <a href="#">&larr; previous</a>
            </li>
            {% endif %}
            <li>
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }} 
            </li>
            {% if page_obj.has_next %}
            <li class="next">
                <a href="?page={{ page_obj.next_page_number }}">next &rarr;</a>
            </li>
            {% else %}
            <li class="next disabled">
                <a href="#">next &rarr;</a>
            </li>
            {% endif %}
        </ul>
    </div>
{% endif %}

templates/signin.html
{% extends "base.html" %}
{% block content %}
<form class="form-signin" action="" method="post">{% csrf_token %}
    <h2 class="form-signin-heading">Please Login</h2>
    <input type="text" class="form-control" placeholder="Email address" autofocus>
    <input type="password" class="form-control" placeholder="Password">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
</form>
{% endblock content %}